### ISSUE TITLE
About The Classifier Code

### ISSUE THREAD

**Issue by Ryanrenqian** [mboudiaf/RePRI-for-Few-Shot-Segmentation#10]
I Noticed that Query Label was used in your code when training a classifier.  Could you tell me why you did that in your code? 

![image](https://user-images.githubusercontent.com/8614325/108801729-75ce4880-75d1-11eb-9431-46662ee1062e.png)

**Comment by mboudiaf** [comment]
The query labels are used for three things : 
1) Obtain the oracle results presented in the paper (here the query labels are used to compute the exact foreground proportion).
2) Derive the valid pixels (i.e label != 255) of the query image to make predictions on.
3) Plot some metrics if desired.

**Comment by sniperwqza** [comment]
> The query labels are used for three things :
> 
> 1. Obtain the oracle results presented in the paper (here the query labels are used to compute the exact foreground proportion).
> 2. Derive the valid pixels (i.e label != 255) of the query image to make predictions on.
> 3. Plot some metrics if desired.

Hello, thanks for your answer.
I have a question about the second usage of query labels. According to my understanding, in the inference stage, we can only use the support images and labels to compute the F/B parameters. Then use the calculated parameters to inference on the query images. The query labels can only be used in calculating the inference loss.
So can you tell me why you use the query labels when computing the F/B parameters?

(The code where you used the query labels to computing the F/B parameters is 
https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/7175525a8c4dd4b703b3bda4f4478f61dd40e113/src/classifier.py#L94)

**Comment by mboudiaf** [comment]
Hello,

Once again, in the main method of the paper :
 1) The query labels are used to obtain the valid pixels https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/7175525a8c4dd4b703b3bda4f4478f61dd40e113/src/classifier.py#L104 (which is not a problem as those only correspond to pixels that have been padded for example, and thus do not give any ground-truth information). We use the predictions of the current classifier at those valid pixels only to compute the F/B param.
2) In the case of the oracle, the query labels are used to compute the oracle proportion: https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/7175525a8c4dd4b703b3bda4f4478f61dd40e113/src/classifier.py#L109 (in this case, this is obviously cheating as you assume you know the true proportion, hence the name "oracle").

Hope it answers you questions.

**Comment by sniperwqza** [comment]
Oh, I got it! Thanks for your answer!
