### ISSUE TITLE
Oracle-RePRI and RePRI

### ISSUE THREAD

**Issue by zhijiejia** [mboudiaf/RePRI-for-Few-Shot-Segmentation#11]
Hi @mboudiaf , What do you mean Oracle-RePRI in table?  What the difference between Oracle-RePRI and RePRI ?

**Comment by mboudiaf** [comment]
Hi,

The oracle case means we assume we have access to the true proportion of foreground/background to be predicted in the query image, as mentioned in the paper:
![image](https://user-images.githubusercontent.com/40210629/110636864-c4a3e280-817a-11eb-8470-f71809fd13c3.png)

Malik

**Comment by zhijiejia** [comment]
Can I understand that only Miou of foreground and background are calculated, not Miou of all categories ？

**Comment by mboudiaf** [comment]
No those two things are unrelated. The \pi parameter is the one used in the loss. You can either "cheat" and set it beforehand to its oracle value, or "learn" it as we do in our main method. 
Regardless, the mIoU is always computed over all categories.
