### ISSUE TITLE
GTX 2080Ti use default config out of mermory

### ISSUE THREAD

**Issue by zhijiejia** [mboudiaf/RePRI-for-Few-Shot-Segmentation#12]
`
bash scripts/train.sh pascal 0 [0,1] 50
`
The first one epoch is ok, but the test phrase will out o memory

**Comment by mboudiaf** [comment]
Hi,

You could try to lower the batch_size_val (which basically represents how many tasks will be treated in parallel during evaluation). By default, I set it to 200, but this is probably too much depending on your GPU. You could set it to as low as 1 if you want it to be more memory efficient. Let me know if that works for you.

Malik

**Comment by zhijiejia** [comment]
Yes, I did it yesterday, it works well, but the val process should not be whith @torch.no_grad ? So that it won't take up the GPU memory

**Comment by mboudiaf** [comment]
Yes, you are 100% right. I dropped it somewhere along the way (as I was experimenting what would happen if you finetune the whole network --bad idea--), and never put it back. I've just added it and pushed. Thanks for noticing.
