### ISSUE TITLE
ImageNet Pretraining

### ISSUE THREAD

**Issue by MSiam** [mboudiaf/RePRI-for-Few-Shot-Segmentation#17]
Hello

Thanks for providing the code and pretrained weights. I had a question regarding Imgenet pretraining, is there a reason why you provide your own pretrained imagenet weights? Are they trained on a separate set of classes in ImageNet not overlapping with Pascal/COCO classes, so not the full Imagenet classes? Or you are using like other FSS methods the imagenet pretraining on all classes.

Thanks

**Comment by mboudiaf** [comment]
Hey !

Thanks for your question. The pre-trained ImageNet models given in this repo are a copy paste of the ones given in https://github.com/dvlab-research/PFENet , and use all classes of ImageNet as other FSS methods. I believe the only reason they specifically provide a checkpoint (as opposed to simply loading it from torchvision) is that there might be a slight architectural difference between the torchvision ResNet-50 and the one they (and consequently we) use. That is to be confirmed though. Hope it helps ! 
Best.

**Comment by MSiam** [comment]
Thanks a lot for your prompt reply and help. One small thing when you mean difference in architecture are you talking about the changed dilation factors in the last 2 layers (layer3, layer4)? Cause it seems to not be in the original pretrained weights when I checked he modifies this after he loads the pretrained weights. Or is there another modification?

**Comment by mboudiaf** [comment]
Hey, I think there is also more significant change in the early layers, with the hyper-parameter `deep_base` defaulted to True: https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/5900a52e27621c5772193599cfc85a730a82f327/src/model/resnet.py#L101 . There may also be some other changes I have not noticed. Please let me know if you find more and I will try to write a small paragraph at the head of the file to summarize these.

**Comment by MSiam** [comment]
Thanks that makes a lot of sense greatly appreciate your help.
