### ISSUE TITLE
validation During training on base classes

### ISSUE THREAD

**Issue by aminpdik** [mboudiaf/RePRI-for-Few-Shot-Segmentation#19]
Thanks for useful code @mboudiaf .

I reviewed the code and noticed that you are using episodic validation during training instead of standard validation. could you please let me know if I am right. 

My second question: how many GPUs  did you use for training? I think batch size was 12.

**Comment by mboudiaf** [comment]
Hey @aminpdik !

Sorry for this late reply. Yes indeed episodic validation was used originally. I also added the option to validation with standard validation using the episodic_val option. I am not exactly sure how results would be impacted by using non episodic validation. I would expect a slight, but not dramatic decrease.

As for the number of GPUs, two standard GPUs (>11 GB) should be enough memory-wise. If you're not limited in GPUs however, I would go for at least 4 to obtain training in reasonable amount of time on COCO. Hope this helps !
