### ISSUE TITLE
KL divergence

### ISSUE THREAD

**Issue by joshmyersdean** [mboudiaf/RePRI-for-Few-Shot-Segmentation#22]
Hello!

Thank you for this work! I was wondering if you could point me to where you are computing the FG-BG proportion KL divergence in your code?

Thank you!

**Comment by mboudiaf** [comment]
Hello ! 

https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/4384594074052b41fa35ab79b79fbf3aecd5ff2f/src/classifier.py#L156

**Comment by joshmyersdean** [comment]
Thank you!
