### ISSUE TITLE
TrainingTime

### ISSUE THREAD

**Issue by AmingWu** [mboudiaf/RePRI-for-Few-Shot-Segmentation#4]
Thanks for your good work. How long does your model need to train?

**Comment by mboudiaf** [comment]
Hi,

For each split, models were trained for 100 epochs for Pascal-5i, and 20 epochs for Coco-20i. Training time heavily depends on the type and number of GPUs you would use. Very roughly speaking, Pascal training on a single GPU would take around half a day, while training for Coco would take several days. 

Best,
Malik
