### ISSUE TITLE
What's your data dir's structure

### ISSUE THREAD

**Issue by 9p15p** [mboudiaf/RePRI-for-Few-Shot-Segmentation#5]
I can't download dataset from google.
please help to show us the structure so that we can do it by ourselves.

**Comment by mboudiaf** [comment]
Hi,

Thanks for bringing this issue. It seems too many people have tried to download it recently. Here is the data/ folder structure:

data
├── coco
│   ├── annotations
│   ├── pycocotools
│   ├── train
│   ├── train2014
│   ├── val
│   └── val2014
└── pascal
    ├── JPEGImages
    └── SegmentationClassAug

I will update the README.md to make it clearer. Thanks again.

**Comment by 9p15p** [comment]
Thank you for your help！

**Comment by Arnaul** [comment]
why there isn't test2014?

**Comment by mboudiaf** [comment]
Because test2014 is not used, since you need the annotations to even just simply be able to form consistent few-shot tasks. Note that this is not a specificity of this paper, all previous literature work with this very config.
