### ISSUE TITLE
How are base classes selected?

### ISSUE THREAD

**Issue by tymatfd** [mboudiaf/RePRI-for-Few-Shot-Segmentation#7]
Hi, thanks for the excellent work. It seems that all objects classes in PASCAL VOC have been used in few-shot segmentation task,  so i am confused about the base classes used in the standard training?, are they still selected from the 20 categories in the PASCAL VOC dataset?

**Comment by mboudiaf** [comment]
Hi, 
For each split, only 15 out of the 20 classes classes are used, and the other 5 are used to testing (and there are 4 splits or 'folds' for each dataset). To know the exact repartition of classes across splits, please refer to https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/f9fb2e4bdfad0d4714bf236cd7aab8852cf6c5de/src/dataset/classes.py#L117

**Comment by tymatfd** [comment]
> Hi,
> For each split, only 15 out of the 20 classes classes are used, and the other 5 are used to testing (and there are 4 splits or 'folds' for each dataset). To know the exact repartition of classes across splits, please refer to
> 
> https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation/blob/f9fb2e4bdfad0d4714bf236cd7aab8852cf6c5de/src/dataset/classes.py#L117

Got it. Thanks for your reply,  I found myself misunderstanding the few-shot segmentation task previously.

**Comment by mboudiaf** [comment]
happy to help :)
