### ISSUE TITLE
About the Experimental Result

### ISSUE THREAD

**Issue by AmingWu** [mboudiaf/RePRI-for-Few-Shot-Segmentation#9]
I run your code on pascal. This is the result of 1-shot case. I find I cannot reproduce your result. Could you give me some advice?

![QQ截图20210219201312](https://user-images.githubusercontent.com/38445175/108506590-036d1800-72f4-11eb-8a37-5061fc94bdb0.png)

**Comment by mboudiaf** [comment]
Which split ? Model trained from scratch or with the provided checkpoints ?

**Comment by AmingWu** [comment]
scratch

**Comment by AmingWu** [comment]
The result of Fold-0, Fold-1, Fold-2, and Fold-3 is 55.47, 66.37, 58.78, and 45.14, which is lower than your report results.

**Comment by mboudiaf** [comment]
Thank for raising this. There is definitely an error somewhere. May come from an error in the training script introduced in one of my latest commits. Let me investigate this and come back to you soon.
